import { Inter } from 'next/font/google'
import Head from 'next/head'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h3 style={{ marginBottom: '20px' }}>PAGES</h3>
        <div style={{ display: "grid", gap: "10px" }} >
          <div><Link href={"page01"} >PAGE-01</Link></div>
          <div><Link href={"page02"} >PAGE-02</Link></div>
          <div><Link href={"page03"} >PAGE-03</Link></div>
          <div><Link href={"page04"} >PAGE-04</Link></div>
          <div><Link href={"page05"} >PAGE-05</Link></div>
          <div><Link href={"page06"} >PAGE-06</Link></div>
          <div><Link href={"page07"} >PAGE-07</Link></div>
          <div><Link href={"page08"} >PAGE-08</Link></div>
          <div><Link href={"page09"} >PAGE-09</Link></div>
          <div><Link href={"page10"} >PAGE-10</Link></div>
          <div><Link href={"page11"} >PAGE-11</Link></div>
          <div><Link href={"page12"} >PAGE-12</Link></div>
          <div><Link href={"page13"} >PAGE-13</Link></div>
          <div><Link href={"page14"} >PAGE-14</Link></div>
          <div><Link href={"page15"} >PAGE-15</Link></div>

        </div>
      </main>
    </>

  )
}
